spark.jars.packages              io.delta:delta-spark_2.13:4.3.0
spark.jars                       /home/ice254/Desktop/dbt_spark/my_dbt_project/jars/postgresql-42.7.3.jar
spark.sql.extensions             io.delta.sql.DeltaSparkSessionExtension
spark.sql.catalog.spark_catalog  org.apache.spark.sql.delta.catalog.DeltaCatalog
spark.sql.warehouse.dir          spark-warehouse
spark.driver.extraJavaOptions    -Dderby.system.home=/home/ice254/Desktop/dbt_spark/my_dbt_project
